UrbanDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("task2.urls", namespace='task2')),
    path('', include('task1.urls', namespace='task3')),
    #path('', include('task3.urls',namespace='task3')),
    #path('', include('task4.urls',namespace='task4')),
    #path('', include('task5.urls', namespace='task5'))
]

task1/urls.py
from django.urls import path
from . import views


app_name = 'task1'
urlpatterns = [
    path('', views.platform, name='platform'),
    path('games/', views.games, name='games'),
    path('cart/', views.cart, name='cart'),
    path('sign_up_django/', views.sign_up_by_django, name='sign_up_django'),
    path('sign_up_html/', views.sign_up_by_html, name='sign_up_html'),

]

templates/first_task/cart.html
{% extends 'first_task/menu.html' %}


{% block pagename %}Корзина{% endblock %}

{% block content %}

<h1>Ваша корзина пуста</h1>
{% endblock %}

templates/first_task/games.html
{% extends 'first_task/menu.html' %}


{% block pagename %}Игры{% endblock %}

{% block content %}
    <h1>Список игр</h1>
    <ul>
        {% for game in games %}
            <li>
                {{ game.title }} | {{ game.description }}. Стоимость: {{ game.price }}
                <button>Купить</button>
            </li>
    {% endfor %}
    </ul>
{% endblock %}

templates/first_task/menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <h1>{% block pagename %}Главная страница{% endblock %}</h1>
</head>
<body>
    <div id="menu">
        {% block menu %}
        <ul>
            <li><a href="{% url 'task1:platform' %}">Главная</a></li>
            <li><a href="{% url 'task1:games' %}">Игры</a></li>
            <li><a href="{% url 'task1:cart' %}">Корзина</a></li>
        </ul>
        {% endblock %}
    </div>

    <div id="content">
        {% block content %}
        <!-- Контент страницы будет здесь -->
        {% endblock %}
    </div>
</body>
</html>

templates/first_task/platform.html
{% extends 'first_task/menu.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Мой сайт</title>
</head>
<body>
    <h1>Главная</h1>
    <ul>
        <li><a href="#">Главная</a></li>
        <li><a href="{% url 'task1:games' %}">Магазин</a></li>
        <li><a href="{% url 'task1:cart' %}">Корзина</a></li>
    </ul>

</body>
</html>

templates/first_task/registration_page.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Регистрация</title>
</head>
<body>
    <h1>Регистрация</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Зарегистрироваться</button>
    </form>

    {% if info.error %}
        <p style="color: red;">{{ info.error }}</p>
    {% endif %}

    {% if message %}
        <p>{{ message }}</p>
    {% endif %}
</body>
</html>