UrbanDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("task2.urls", namespace='task2')),
    path('', include('task1.urls', namespace='task3')),
    #path('', include('task3.urls',namespace='task3')),
    #path('', include('task4.urls',namespace='task4')),
    #path('', include('task5.urls', namespace='task5'))
]

task1/urls.py
from django.urls import path
from . import views


app_name = 'task1'
urlpatterns = [
    path('', views.platform, name='platform'),
    path('games/', views.games, name='games'),
    path('cart/', views.cart, name='cart'),
    path('sign_up_django/', views.sign_up_by_django, name='sign_up_django'),
    path('sign_up_html/', views.sign_up_by_html, name='sign_up_html'),

]

templates/third_task/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Корзина</h1>

    <p>Ваша корзина пока пуста</p>

    <a href="{% url 'task3:platform' %}"><button>Вернуться на главную</button></a>


</body>
</html>

templates/third_task/games.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Игры</h1>
    <ul>
        <li>Baldur’s Gate III</li><button>Купить</button>
        <li>Ведьмак 3</li><button>Купить</button>
        <li>Mass Effect 3</li><button>Купить</button>
    </ul>
    <a href="{% url 'task3:platform' %}"><button>Вернуться на главную</button></a>

</body>
</html>

templates/third_task/platform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Мой сайт</title>
</head>
<body>
    <h1>Главная</h1>
    <ul>
        <li><a href="#">Главная</a></li>
        <li><a href="{% url 'task3:games' %}">Магазин</a></li>
        <li><a href="{% url 'task3:cart' %}">Корзина</a></li>
    </ul>

</body>
</html>